project:
  type: book
  output-dir: docs
  
book:
  title: "Estadística Aplicada con R"
  author: "MODAE"
  date: " 11 junio 2025"
  subtitle: "Guía de estadística aplicada con R"
  
  chapters:
    - index.qmd
    - intro.qmd
    - part: Contenidos
      chapters: 
        - Preliminares.qmd
        - Contrastes_de_hipotesis.qmd 
        - ANOVA.qmd
        - Regresion.qmd
        - Supervivencia.qmd
        - Modelos_lineales.qmd


bibliography: references.bib

format:
  html:
    theme:
      light: materia
      dark: darkly
    css: custom.css
    cover-image: 100_prisoners_boxes_fixed.png
    toggle: true


  pdf:
    documentclass: scrreprt
   
editor: visual
lang: es
