---
title: "Curso de R para la generación de informes"
author: 'Curso de R: Planificación'
date: "2022-09-21"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Curso De R y Rstudio.

Uno los programas de análisis de datos, ciencia de datos, presentación de informes es [R-project](https://www.r-project.org/). Es un software/entorno muy amplio de  manipulación de datos libre, presentación de informes, con una fuerte (aunque  no única) componente estadística. Es mantenido por la comunidad de R-project

El entorno de desarrollo integrado (IDE) más popular es Rstudio Desktop de la empresa [Rstudio](https://www.rstudio.com/); en su versión desktop básica es gratuito.

Rstudio  ha promovido junto a la comunidad de R-project una serie de librerías libres: las llamadas *tidyverse*. Además podemos disponer de *Shiny* un programa para generar informes interactivos (en este caso la licencia web es limitada). Además ha generado sistemas sencillos de generación de informes en los que se combina código e información. Como son: [Rmarkdown](https://rmarkdown.rstudio.com/) y [Quarto ](https://quarto.org/).


Los  enlaces para la descarga de estos programa son:

* [R-project](https://www.r-project.org/). Para la descarga hay que escoger uno de los mirrors del cran_ [Download](https://cran.r-project.org/mirrors.html)
* [Rstudio](rstudio.com). [Download](https://www.rstudio.com/products/rstudio/)



Para empezar a manejar todos los programas de este entorno los manuales básicos son:


Uno de las más populares es el de coursera https://www.datacamp.com/courses/introduction-to-the-tidyverse


* Una [página con los  manuales básicos ](https://www.tidyverse.org/learn/) desde [R4DS](https://r4ds.had.co.nz/) a [Data manipulation whith R](https://itsalocke.com/files/DataManipulationinR.pdf)

* [Tidyverse](https://www.tidyverse.org/)

* Generación informes con rmarkdown [Rmarkdown book de  Yihuie Xie, J.J. Allaire, Garret Grolemund](https://bookdown.org/yihui/rmarkdown/)

* Generación informes con quarto [Manual de quarto](https://quarto.org/)






